server:
  port: 8100
  servlet:
    context-path: /six
spring:                                                                                                   
  mvc:
    throw-exception-if-no-handler-found: true  
  application:
    name: academy-6-microservice
  jpa:
    hibernate:
      ddl-auto: update
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: UTC
  datasource:
    url: jdbc:mysql://localhost:3306/academy?useLegacyDatetimeCode=false
    username: academy
    password: academy
  security:
    user:
      name: academy
      password: academy
      roles: manager
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  server:
    port: 9100
    base-path: /health